name: CI/CD GreenCity

on:
  push:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

  pull_request:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

  # for debugging purposes
  workflow_dispatch:

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'oracle'  # 'temurin'
  SETUP_JAVA_CACHE: 'maven'

jobs:

  test:
    name: Run Backend Unit Tests
    runs-on: ubuntu-latest
#    container: maven:3.9.6-eclipse-temurin-21-alpine
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11     # v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93   # v4.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}
      #          cache: ${{ env.SETUP_JAVA_CACHE }}

      #      - name: Customize Maven version
      #        uses: stCarolas/setup-maven@v5
      #        with:
      #          maven-version: 3.9.2
      #

      - name: Check Java and Maven versions, and clean local Maven repository
        run: |
          java --version
          mvn --version
          mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout
          echo "\nBEFORE TESTS:\n"
          df -h
          du -sh $JAVA_HOME
          du -sh ~/.m2/repository

      #          rm -rf $(mvn help:evaluate -Dexpression=settings.localRepository -q -DforceStdout)
      ##          rm -rf ~/.m2/repository

      - name: Run Unit Tests via Maven
        run: mvn --batch-mode --no-transfer-progress dependency:list clean test

      - name: Check Java and Maven versions, and clean local Maven repository
        if: success() || failure()
        run: |
          echo "\nAFTER TESTS:\n"
          df -h
          du -sh $JAVA_HOME
          du -sh ~/.m2/repository

      - name: Upload JUnit Test Report as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        if: success() || failure()
        with:
          name: JUnit Test Report
          path: |
            core/target/surefire-reports/*.xml
            service/target/surefire-reports/*.xml
            service-api/target/surefire-reports/*.xml

      - name: Publish JUnit Test Reports
        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
        if: success() || failure()
        with:
          name: JUnit Test Reports
          path: |
            **/target/surefire-reports/*.xml
          reporter: java-junit

  build:
    name: Build Backend
    needs: test
    runs-on: ubuntu-latest
    container: maven:3.9.6-eclipse-temurin-21-alpine
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11     # v4.1.1

#      - name: Set up JDK
#        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93   # v4.0.0
#        with:
#          java-version: ${{ env.JAVA_VERSION }}
#          distribution: ${{ env.JAVA_DISTRIBUTION }}
#          cache: ${{ env.SETUP_JAVA_CACHE }}

      - name: Build a JAR package via Maven
        run: mvn --batch-mode --no-transfer-progress -DskipTests dependency:list clean package

      - name: Upload JAR package as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        if: success() || failure()
        with:
          name: Archived JAR packages
          path: |
            core/target/core-1.0-SNAPSHOT.jar
            dao/target/dao-1.0-SNAPSHOT.jar
            service/target/service-1.0-SNAPSHOT.jar
            service-api/target/service-api-1.0-SNAPSHOT.jar
