name: CI/CD GreenCity

on:
  push:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

  pull_request:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'oracle'

jobs:

  test:
    name: Run Backend Unit Tests
    # runs-on: ubuntu-latest  # sometimes works
    runs-on: ubuntu-22.04  # sometimes works
    # runs-on: ubuntu-20.04  # works
    steps:
      - name: Checkout backend repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11     # v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93   # v4.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

      - name: Run Unit Tests and Build
        run: mvn --batch-mode --no-transfer-progress dependency:list clean test

      - name: Upload JUnit Test Report as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        if: success() || failure()
        with:
          name: JUnit Test Report
          path: |
            **/target/surefire-reports/*.xml

      - name: Publish JUnit Test Reports
        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
        if: success() || failure()
        with:
          name: JUnit Test Reports
          path: |
            **/target/surefire-reports/*.xml
          reporter: java-junit

      - name: Build a JAR package via Maven
        run: mvn --batch-mode --no-transfer-progress -DskipTests dependency:tree clean package

      - name: Upload JAR packages as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        with:
          name: JAR Packages
          path: |
            **/target/*.jar