name: CI/CD GreenCity

on:
  push:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

  pull_request:
    branches:
      - main
      - master
      - dev_java21
      - my_dev_java21

env:
  JAVA_VERSION: 21
  JAVA_DISTRIBUTION: 'oracle'

jobs:

  test_and_build:
    name: Test and Build
#    environment: test
    runs-on: ubuntu-20.04     # always works
    # runs-on: ubuntu-latest  # sometimes works
    # runs-on: ubuntu-22.04   # sometimes works

    steps:
      - name: Checkout backend repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11     # v4.1.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of SonarQube reporting
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@387ac29b308b003ca37ba93a6cab5eb57c8f5f93   # v4.0.0
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRIBUTION }}

#      - name: Run Unit Tests
#        run: mvn --batch-mode --no-transfer-progress dependency:list clean test

      - name: Run Unit Tests with Coverage and Build a JAR package
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn --batch-mode --no-transfer-progress org.jacoco:jacoco-maven-plugin:prepare-agent clean package sonar:sonar \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.organization=lerkasan \
            -Dsonar.projectKey=lerkasan_GreenCityMVP21 \
            -Dsonar.pullrequest.base=${{ github.event.pull_request.base.ref }} \
            -Dsonar.pullrequest.branch=${{ github.event.pull_request.head.ref }} \
            -Dsonar.pullrequest.key=${{ github.event.pull_request.number }}
#           -Dsonar.pullrequest.github.summary_comment=true # default value is true

      - name: Publish JUnit Test Reports
        uses: dorny/test-reporter@eaa763f6ffc21c7a37837f56cd5f9737f27fc6c8   # v1.8.0
        if: success() || failure()
        with:
          name: JUnit Test Reports
          path: |
            **/target/surefire-reports/*.xml
          reporter: java-junit

#      - name: Run SonarCloud Scan
#        uses: sonarsource/sonarcloud-github-action@master
#        with:
#          args: >
#            -Dsonar.organization=lerkasan
#            -Dsonar.projectKey=GreenCityMVP21
#            -Dsonar.host.url=https://sonarcloud.io
#            -Dsonar.newCode.referenceBranch=my_dev_java21
#            -Dsonar.pullrequest.base=my_dev_java21

#            -Dsonar.projectVersion=
#            -Dsonar.binaries=target/classes
#            -Dsonar.dynamicAnalysis=reuseReports
#        env:
##          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Upload JUnit Test Report as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        if: success() || failure()
        with:
          name: JUnit Test Report
          path: |
            **/target/surefire-reports/*.xml

      - name: Upload JaCoCo Coverage Report as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        if: success() || failure()
        with:
          name: JaCoCo Coverage Report
          path: |
            **/target/site/jacoco

#      - name: Build a JAR package via Maven
#        run: mvn --batch-mode --no-transfer-progress -DskipTests dependency:tree clean package

      - name: Upload JAR packages as Artifact
        uses: actions/upload-artifact@5d5d22a31266ced268874388b861e4b58bb5c2f3   # v4.3.1
        with:
          name: JAR Packages
          path: |
            **/target/*.jar